### ISSUE TITLE
RefundAddressTransaction Is Missing

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#542]
When an order is refunded, it's expected that calling the order api will return a value for RefundAddressTransaction.

PaymentAddressTransactions appears to be output as expected, but no value for RefundAddressTransaction is shown. 

The order does have a refund section (with an orderID, timestamp, and memo), and the state returned is "REFUNDED."

The refund appears in the buyer's wallet.

**Comment by rmisio** [comment]
I originally found this scenario to be happening and then when you couldn't replicate it, I asked Josh if he could try. He did and was able to replicate it? What additional validation does this need?

**Comment by rmisio** [comment]
@cpacia FWIW, you're welcome to use the current master version of the client and give this a try on your own.

**Comment by cpacia** [comment]
Fixed

**Comment by rmisio** [comment]
@jjeffryes just ran into this issue again. Looks like this one is not fixed.

**Comment by jjeffryes** [comment]
I was actually running into a new bug, I traced it down and posted #565

**Comment by rmisio** [comment]
This is still an issue. I just bought a moderated listing, opened a dispute, had the mod resolve the dispute and accepted the payout. Afterwards, the order state was `RESOLVED` and the order contains a `disputeAcceptance` event... but there is no `RefundAddressTransaction` transaction object and therefore the UI cannot show a record of the refund transaction.

FWIW, all three parties were online as this was happening.
