### ISSUE TITLE
Updating inventory via API fails with 'cannot unmarshal object'

### ISSUE THREAD

**Issue by cliftonts** [OpenBazaar/openbazaar-go#786]
Apologies for submitting yet another issue, but there doesn't seem to be anywhere else to turn.
Using the example code in the API documentation fails with "reason": "json: cannot unmarshal object into Go value of type []api.inv"

I have used the exact example below and I have also substituted the details in the payload for a listing in my store.
```
import requests

url = "{{http}}://{{url}}:{{port}}/ob/inventory"

payload = "{\n\t\"slug\": \"/cool_tshirt/red/xl\",\n\t\"quantity\": 17\n}"
headers = {'content-type': 'application/json'}

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
```

**Comment by cpacia** [comment]
I'll take a look into it. I don't think the client is using that endpoint. It's just using PUT /ob/listing to update inventory I believe.

**Comment by cliftonts** [comment]
Thanks. I had a play with that but I'm not sure exactly how to format the payload to be accepted.

**Comment by cliftonts** [comment]
Does nobody know how this API works?

**Comment by cpacia** [comment]
@cliftonts looks like it's expecting a list so that multiple can be updated at once:

```
curl -d '[{"slug":"christmas-sweather", "quantity": 22}]' http://localhost:4002/ob/inventory
```

**Comment by cliftonts** [comment]
I give up, this apparently isn't possible!

**Comment by hoffmabc** [comment]
Is that true @cpacia? It’s not possible?

**Comment by christroutner** [comment]
* [Here is a gist](https://gist.github.com/christroutner/829bf65eec73dfbc7beb44699dddba0a) showing how to manipulate a listing using jQuery.

* [Here is an NPM library](https://github.com/P2PVPS/openbazaar-node) that I published about a week ago to help JavaScript programmers work with the API.

**Comment by cliftonts** [comment]
Thank you for that but I still don't see anything in there about updating listings. All I have gotten so far is half a solution which doesn't work and then the issue closed down.
